Add Mealie to Easypanel 🎉
easypanel-io/templates pull request #148
Opened 2022-12-11 19:32 UTC by Supernova3339

This adds the popular open-source recipe book, Mealie to Easypanel!
Tested successfully on `ARM` and `AMD` CPUs.

2023-01-02 18:28 UTC, deiucanta requested changes
Also, make sure you remove the changes in `package-lock.json` and `yarn.lock`. No need to update those for a template

2023-01-02 18:28 UTC, deiucanta commented on templates/mealie/index.ts
> +        `DEFAULT_EMAIL=changeme@easypanel.io`,
If this is required, please extract it in a separate field

2023-01-02 18:28 UTC, deiucanta commented on templates/mealie/index.ts
> +            domains: [
This doesn't seem to be properly formatted.

2023-01-02 20:17 UTC, Supernova3339 commented
> Also, make sure you remove the changes in `package-lock.json` and `yarn.lock`. No need to update those for a template

I always run npm I, will make sure to not PR those as well

2023-01-08 14:39 UTC, deiucanta commented
Merged manually

2023-01-08 14:39 UTC, closed without merging