Add Cockpit to Easypanel 🎉
easypanel-io/templates pull request #288
Opened 2023-03-20 13:16 UTC by Supernova3339

2023-03-20 13:34 UTC, Ponkhy commented
Hey, is this template for [Cockpit-HQ](https://hub.docker.com/r/cockpithq/cockpit) or the old v1 [Cockpit](https://hub.docker.com/r/agentejo/cockpit/)?

2023-03-20 15:13 UTC, Ponkhy commented
> brand new v2 - built a custom image for it on easypanel-community/docker-cockpit-cms

What is the difference between the custom and official v2 image?

2023-03-21 17:09 UTC, Supernova3339 commented
> > brand new v2 - built a custom image for it on easypanel-community/docker-cockpit-cms
> 
> What is the difference between the custom and official v2 image?

there isn't a v2 image - only v1. v2 doesn't go up to the latest version, it goes up to 2.11.5

2023-03-24 23:23 UTC, Ponkhy commented
> > > brand new v2 - built a custom image for it on easypanel-community/docker-cockpit-cms
> > 
> > 
> > What is the difference between the custom and official v2 image?
> 
> there isn't a v2 image - only v1. v2 doesn't go up to the latest version, it goes up to 2.11.5

Wouldn't this image [core-2.4.1](https://hub.docker.com/layers/cockpithq/cockpit/core-2.4.1/images/sha256-b58539d5244b3f6ed07368a39ba606e8a887f1400e8e1f1b4a024cebed2dea69?context=explore) be the one for the latest version [2.4.1](https://github.com/Cockpit-HQ/Cockpit/releases/tag/2.4.1), or am I mistaken?

2023-03-26 05:58 UTC, Supernova3339 commented
> > > > brand new v2 - built a custom image for it on easypanel-community/docker-cockpit-cms
> > > 
> > > 
> > > What is the difference between the custom and official v2 image?
> > 
> > 
> > there isn't a v2 image - only v1. v2 doesn't go up to the latest version, it goes up to 2.11.5
> 
> Wouldn't this image [core-2.4.1](https://hub.docker.com/layers/cockpithq/cockpit/core-2.4.1/images/sha256-b58539d5244b3f6ed07368a39ba606e8a887f1400e8e1f1b4a024cebed2dea69?context=explore) be the one for the latest version [2.4.1](https://github.com/Cockpit-HQ/Cockpit/releases/tag/2.4.1), or am I mistaken?

its for 2.4.1

2023-03-26 19:21 UTC, Ponkhy requested changes
The data doesn't seem to be persistent after a restart, at least the login. Could you please look into it?

2023-03-26 19:21 UTC, Ponkhy commented on templates/cockpit/index.ts
> +          mountPath: "/var/ww/html"
```suggestion
          mountPath: "/var/www/html"
```

2023-03-26 20:32 UTC, Supernova3339 commented
could you attempt deployment to confirm? I've just tried and had no
problems.

On Sun, Mar 26, 2023 at 7:21 PM Ponkhy ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> The data doesn't seem to be persistent after a restart, at least the
> login. Could you please look into it?
> ------------------------------
>
> In templates/cockpit/index.ts
> <https://github.com/easypanel-io/templates/pull/288#discussion_r1148626284>
> :
>
> > +        `COCKPIT_DATABASE_SERVER=mongodb://mongo:${mongoPassword}:27017`,
> +        `COCKPIT_DATABASE_NAME=${input.projectName}_${input.databaseServiceName}`
> +      ].join("\n"),
> +      source: {
> +        type: "image",
> +        image: input.appServiceImage,
> +      },
> +      proxy: {
> +        port: 80,
> +        secure: true,
> +      },
> +      mounts: [
> +        {
> +          type: "volume",
> +          name: "html",
> +          mountPath: "/var/ww/html"
>
> ⬇️ Suggested change
>
> -          mountPath: "/var/ww/html"
> +          mountPath: "/var/www/html"
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/easypanel-io/templates/pull/288#pullrequestreview-1358095787>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APESZJU6BTPF7CXVXN4VBO3W6CQOLANCNFSM6AAAAAAWBCKR2I>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2023-03-27 07:42 UTC, Ponkhy commented
> could you attempt deployment to confirm? I've just tried and had no problems.

Yes I can confirm it, you can try it yourself by just stopping the app and start it again, after that you'll not be able to login again.
Although I think the MongoDB connections string is also wrong, or is not even used.

2023-04-09 12:56 UTC, Ponkhy requested changes
It seems to work now, although I don't think that it actually needs/uses the MongoDB.

2023-04-09 12:56 UTC, Ponkhy commented on templates/cockpit/index.ts
> +        `COCKPIT_DATABASE_NAME=${input.projectName}_${input.databaseServiceName}`
```suggestion
        `COCKPIT_DATABASE_SERVER=mongodb://mongo:${mongoPassword}@${input.projectName}_${input.databaseServiceName}:27017`,
        `COCKPIT_DATABASE_NAME=${input.projectName}`
```

2023-06-30 18:58 UTC, merged