Add Octobox to Easypanel 🎉
easypanel-io/templates pull request #299
Opened 2023-03-22 13:40 UTC by Supernova3339

2023-03-22 17:18 UTC, Ponkhy requested changes
When it starts the Easypanel domain will be blocked. Maybe disable it or add a domain property and add it to the allow list?

2023-03-22 17:18 UTC, Ponkhy commented on templates/octobox/index.ts
> +        `RAILS_ENV=production`,
This either needs to be changed to `development` or the `SECRET_KEY_BASE` env needs to be added.

2023-03-22 17:18 UTC, Ponkhy commented on templates/octobox/index.ts
> +        `REDIS_URL=PAPERLESS_REDIS=redis://default:${redisPassword}@${input.projectName}_${input.redisServiceName}:6379`,
Redis Server deployment is missing.

2023-03-22 17:29 UTC, Supernova3339 commented
Whoops I'll fix that sorry

On Wed, Mar 22, 2023 at 5:19 PM Ponkhy ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> When it starts the Easypanel domain will be blocked. Maybe disable it or
> add a domain property and add it to the allow list?
> ------------------------------
>
> In templates/octobox/index.ts
> <https://github.com/easypanel-io/templates/pull/299#discussion_r1145168015>
> :
>
> > +  Services
> +} from "~templates-utils";
> +import { Input } from "./meta";
> +
> +export function generate(input: Input): Output {
> +  const services: Services = [];
> +  const databasePassword = randomPassword();
> +  const redisPassword = randomPassword();
> +
> +  services.push({
> +    type: "app",
> +    data: {
> +      projectName: input.projectName,
> +      serviceName: input.appServiceName,
> +      env: [
> +        `RAILS_ENV=production`,
>
> This either needs to be changed to development or the SECRET_KEY_BASE env
> needs to be added.
> ------------------------------
>
> In templates/octobox/index.ts
> <https://github.com/easypanel-io/templates/pull/299#discussion_r1145168739>
> :
>
> > +  const redisPassword = randomPassword();
> +
> +  services.push({
> +    type: "app",
> +    data: {
> +      projectName: input.projectName,
> +      serviceName: input.appServiceName,
> +      env: [
> +        `RAILS_ENV=production`,
> +        `GITHUB_CLIENT_ID=${input.githubClient}`,
> +        `GITHUB_CLIENT_SECRET=${input.githubSecret}`,
> +        `OCTOBOX_DATABASE_NAME=${input.projectName}`,
> +        `OCTOBOX_DATABASE_USERNAME=postgres`,
> +        `OCTOBOX_DATABASE_PASSWORD=${databasePassword}`,
> +        `OCTOBOX_DATABASE_HOST=${input.projectName}_${input.databaseServiceName}`,
> +        `REDIS_URL=PAPERLESS_REDIS=redis://default:${redisPassword}@${input.projectName}_${input.redisServiceName}:6379`,
>
> Redis Server deployment is missing.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/easypanel-io/templates/pull/299#pullrequestreview-1353122323>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APESZJWIX2OZ7DL6TEG4DPTW5MYA7ANCNFSM6AAAAAAWD2XU24>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-03-25 00:08 UTC, Ponkhy commented
The following env also need to be added `ALLOW_ALL_HOSTNAMES=true`.

2023-06-30 18:47 UTC, deiucanta commented
@Supernova3339 do you want to fix this?

2023-07-01 04:37 UTC, Supernova3339 commented
> @Supernova3339 do you want to fix this?

Will be fixed ASAP

2023-07-01 08:20 UTC, merged