Add Easyshortener to Easypanel 🎉
easypanel-io/templates pull request #304
Opened 2023-03-23 23:07 UTC by Supernova3339

An announcement in discord for this one would be kinda cool as I've been working on this for a little bit.
New APP from the Easypanel Community

2023-03-23 23:08 UTC, Supernova3339 commented
An announcement in discord for this one would be kinda cool as I've been working on this for a little bit.

2023-03-25 00:17 UTC, Ponkhy requested changes
The following needs to be added in order to load the assets.
```js
domains: [
  {
    name: input.domain,
  },
],
```

2023-03-25 00:17 UTC, Ponkhy commented on templates/easyshortener/index.ts
> +        `# Database`,
```suggestion
```

2023-03-25 00:17 UTC, Ponkhy commented on templates/easyshortener/index.ts
> +        `# Configuration`,
```suggestion
```

2023-03-25 00:40 UTC, Supernova3339 commented on templates/easyshortener/index.ts
> +        `APP_KEY=base64:YzRhdzY1aWUxa3Q4bDJhbWJ6ajdycmUya3h5MzdrcmM=`,
There isn't a function for it yet

2023-03-25 00:42 UTC, Supernova3339 commented
> The following needs to be added in order to load the assets.
> ```js
> domains: [
>   {
>     name: input.domain,
>   },
> ],
> ```

I'll add that ASAP when I get home

2023-03-28 06:24 UTC, Ponkhy approved these changes
LGTM

2023-06-30 18:44 UTC, merged