Add muse template (discord music bot)
easypanel-io/templates pull request #327
Opened 2023-03-30 18:33 UTC by d8vjork

2023-04-01 15:04 UTC, Ponkhy requested changes
Please also add a new env. `DATA_DIR=./data` and the according volume.

2023-04-01 15:04 UTC, Ponkhy commented on templates/muse/index.ts
> +        image: "codetheweb/muse:2.1"
```suggestion
        image: input.appServiceImage
```

2023-04-01 15:04 UTC, Ponkhy commented on templates/muse/meta.yaml
> +    - appServiceName
```suggestion
    - appServiceName
    - appServiceImage
```

2023-04-01 15:04 UTC, Ponkhy commented on templates/muse/meta.yaml
> +      title: App Service Image
```suggestion
    appServiceImage:
      type: string
      title: App Service Image
      default: codetheweb/muse:2.2.2
```

2023-04-01 20:31 UTC, d8vjork commented
Thanks for the details @Ponkhy !

2023-04-09 13:16 UTC, Ponkhy commented on templates/muse/index.ts
> +        `DISCORD_TOKEN=${input.discordToken}`,
```suggestion
        `DATA_DIR=./data`,
        `DISCORD_TOKEN=${input.discordToken}`,
```

2023-06-30 18:37 UTC, deiucanta commented
@d8vjork @Ponkhy is this good to be merged?

2023-06-30 18:39 UTC, d8vjork commented
> @d8vjork @Ponkhy is this good to be merged?

I think so, go ahead

2023-06-30 18:43 UTC, merged

2023-06-30 18:43 UTC, deiucanta commented
Awesome, thanks!