Add Redash to Easypanel
easypanel-io/templates pull request #336
Opened 2023-04-06 10:57 UTC by tboulogne

2023-04-06 12:21 UTC, berksmbl requested changes
The Scheduler and Worker services may not be functioning correctly.

2023-04-06 12:21 UTC, berksmbl commented on templates/redash/meta.yaml
> +      default: redash
The project name should not be given as a default value.

2023-04-06 12:21 UTC, berksmbl commented on templates/redash/index.ts
> +        `REDASH_MAIL_USE_${input.transport}=true`,
SSL or TLS should not be mandatory. An option for None should be included.

2023-07-01 08:31 UTC, deiucanta commented on templates/redash/index.ts
> +        `REDASH_SECRET_KEY=${secretkey}`,
can you extract the common env vars into a separate array? this way you don't repeat the same vars over and over again

2023-09-09 15:04 UTC, andyzukunft commented
Hey all, as far as I can tell the only thing remaining is the environment variables to be project-global. Is that correct?

2026-04-22 15:49 UTC, Ahson-Shaikh commented
Closing this and creating a separate PR for this.

2026-04-22 15:49 UTC, closed without merging