add: ERPNext
easypanel-io/templates pull request #448
Opened 2023-09-21 15:02 UTC by matbrgz

**Description:**
This pull request addresses the initial steps required to integrate ERPNext into our project. ERPNext is a comprehensive Enterprise Resource Planning (ERP) system that promises to enhance our business operations across various functions.

**Changes:**
- Added initial configuration files for ERPNext integration.

**Request for Assistance:**
I'm seeking assistance from team members who are familiar with ERPNext to guide me through the integration process. Specifically, I'd appreciate your expertise in:

1. Configuring ERPNext to align with our specific business processes.
2. Advising on best practices for data synchronization and workflow management.

Your insights and assistance in these areas will be invaluable in ensuring a successful implementation of ERPNext into our project.

**Checklist:**

- [x] Added initial configuration files for ERPNext.
- [ ] Implemented basic API calls for communication.

**Additional Notes:**

Your expertise in ERPNext will greatly contribute to the seamless integration of this powerful tool into our project. Please review the changes and provide your feedback and guidance at your earliest convenience.

2023-09-22 03:47 UTC, Supernova3339 requested changes
Please make the above changes.

2023-09-22 03:47 UTC, Supernova3339 commented on templates/erpnext/index.ts
This is weblate

2023-09-22 03:47 UTC, Supernova3339 commented on templates/erpnext/meta.yaml
This is also weblate

2023-09-22 14:43 UTC, matbrgz commented
Based on https://github.com/frappe/frappe_docker/blob/main/pwd.yml I finish this integration.

2024-09-16 07:58 UTC, ckonkel commented
So is ERPNEXT gonna get added?

2024-09-17 01:38 UTC, Supernova3339 approved these changes
LGTM! Thanks for making the changes.

2024-09-18 05:11 UTC, matbrgz commented
@Supernova3339 rdy to go!

2024-12-01 19:14 UTC, jchambo commented
When is this coming?

2025-04-04 19:59 UTC, Angelosecu commented
I need this, it's an ERP that has a lot to offer to the community, it would be good to have a template as soon as possible.

2025-04-04 19:59 UTC, Angelosecu commented
I need this, it's an ERP that has a lot to offer the community, it would be nice to have a template as soon as possible.

2026-04-22 15:20 UTC, Ahson-Shaikh commented
Checks are still failing. @matbrgz - Please fix them

2026-04-22 16:06 UTC, merged