add: Zulip
easypanel-io/templates pull request #449
Opened 2023-09-21 15:22 UTC by matbrgz

**Description:**
This pull request aims to integrate Zulip, a powerful team collaboration platform, into our project. By incorporating Zulip, we can enhance our team communication with organized, topic-based discussions and improved real-time and asynchronous messaging capabilities.

**Changes:**
- Added necessary files and configurations for Zulip integration.
- Integrated Zulip's messaging functionality into our project's communication modules.

**Request for Review:**

I kindly request a review of this pull request to ensure a smooth integration of Zulip into our project. Your feedback on the changes and suggestions for any additional improvements would be greatly appreciated.

**Checklist:**
- [x] Added Zulip integration files and configurations.
- [ ] Integrated Zulip's messaging functionality.

**Additional Notes:**
With the integration of Zulip, we anticipate a more efficient and focused communication process for our team. Please review the changes and let me know if any further adjustments are needed.

2023-09-22 03:45 UTC, Supernova3339 requested changes
This template is just weblate. Can you fix that?

2023-09-22 03:45 UTC, Supernova3339 commented on templates/zulip/index.ts
This is weblate

2023-09-22 03:45 UTC, Supernova3339 commented on templates/zulip/meta.yaml
This is also weblate

2023-09-22 16:46 UTC, matbrgz commented
https://github.com/zulip/docker-zulip/blob/main/docker-compose.yml

2025-06-15 02:53 UTC, LivioGama commented
@matbrgz I finished the work in https://github.com/matbrgz/templates/pull/1
Hope you will merge it, I didn't want to keep you out of the loop. Also added you to the contributors.

2026-04-22 15:11 UTC, Ahson-Shaikh commented
Check are still failing @matbrgz - Would you be able to resolve it, otherwise, I can give it a shot as well.

2026-04-23 19:00 UTC, Ahson-Shaikh commented
I have created a separated PR, fixed some issues and now the template is functional. I have also given you the credit for suggesting and contributing for Easypanel. This is the PR: https://github.com/easypanel-io/templates/pull/1351. 

I'm closing this PR.

2026-04-23 19:00 UTC, closed without merging