add: Komiser *WIP*
easypanel-io/templates pull request #450
Opened 2023-09-21 15:29 UTC by matbrgz

2023-09-22 03:43 UTC, Supernova3339 requested changes
Please address the above concerns.

2023-09-22 03:43 UTC, Supernova3339 commented on templates/komiser/meta.yaml
In your **appServiceImage** you have gogs, this is already a template.

2023-09-22 04:13 UTC, Supernova3339 requested changes

2023-09-22 04:13 UTC, Supernova3339 commented on templates/komiser/meta.yaml
Please change the default to something like other templates, the service  name is not the actual image. You can specify the image the same way you would do with any other template.

Example of default: `komiser-db`

2023-09-22 04:45 UTC, Supernova3339 requested changes

2023-09-22 04:45 UTC, Supernova3339 commented on templates/komiser/index.ts
No development command `komiser start`
Komiser requires configuration. Please use a `config.toml` or environment variables.

You WILL need to insert config.toml yourself, please check the Plausible template for an example.

2023-09-22 04:45 UTC, Supernova3339 commented on templates/komiser/meta.yaml
You have to configure a cloud provider via config, please add this to instructions.

2023-09-22 05:23 UTC, matbrgz commented on templates/komiser/meta.yaml
Any idea how to give instructions about it?

2023-09-22 05:23 UTC, matbrgz commented on templates/komiser/index.ts
Doing

2026-04-22 14:57 UTC, Ahson-Shaikh commented
Hi @matbrgz, we already have this template. Thanks for the efforts.

2026-04-22 14:57 UTC, closed without merging