add: erxes *WIP*
easypanel-io/templates pull request #451
Opened 2023-09-21 15:37 UTC by matbrgz

**Description:**

This pull request aims to integrate erxes, a versatile Growth Marketing Platform, into our project. By incorporating erxes, we aim to streamline customer engagement, improve communication strategies, and enhance our overall customer relationship management.

**Changes:**

- Added necessary files and configurations for erxes integration.
- Integrated erxes' functionality for customer engagement, marketing automation, and team collaboration.

**Request for Review:**

I kindly request a review of this pull request to ensure seamless integration with erxes. Feedback on the changes, as well as any suggestions for further improvements, would be highly valuable.

**Checklist:**

- [x] Added erxes integration files and configurations.
- [ ] Integrated erxes' Growth Marketing Platform functionality.

**Additional Notes:**

With the integration of erxes, we anticipate improved customer engagement and streamlined communication strategies. Please review the changes and let me know if there are any additional adjustments or considerations needed.

2023-09-22 03:41 UTC, Supernova3339 requested changes
Please fix this at an appropriate time.

2023-09-22 03:41 UTC, Supernova3339 commented on templates/erxes/index.ts
Why isn't postgres available if it's in the meta.yaml?

2023-09-22 03:41 UTC, Supernova3339 commented on templates/erxes/meta.yaml
Postgres available, index.ts does nothing with it. This will throw an error.

2023-09-22 03:50 UTC, matbrgz commented
This one is the hardest one, could you please make it for me? I will watch and learn.

https://erxes.io/
https://docs.erxes.io/docs/intro/
https://docs.erxes.io/docs/introduction/architecture

2026-04-22 14:56 UTC, Ahson-Shaikh commented
Hi @matbrgz, no worries. I'll take care of it now.

2026-04-22 14:56 UTC, closed without merging