add: Trudesk *WIP*
easypanel-io/templates pull request #452
Opened 2023-09-21 15:42 UTC by matbrgz

**Description:**

This pull request proposes the integration of Trudesk, an open-source helpdesk and customer support platform, into our project. By incorporating Trudesk, we aim to enhance our customer service operations, streamline ticket management, and improve overall response times.

**Changes:**

- Added necessary files and configurations for Trudesk integration.
- Integrated Trudesk's functionality for ticket management, multi-channel support, and team collaboration.

**Request for Review:**

I kindly request a thorough review of this pull request to ensure a seamless integration with Trudesk. Feedback on the changes, as well as any suggestions for further improvements, would be highly valuable.

**Checklist:**

- [x] Added Trudesk integration files and configurations.
- [ ] Integrated Trudesk's helpdesk and customer support functionality.

**Additional Notes:**

With the integration of Trudesk, we anticipate improved efficiency in handling customer inquiries and providing timely support. Please review the changes and let me know if there are any additional adjustments or considerations needed.

2023-09-22 03:39 UTC, Supernova3339 requested changes
Why is there a deployment command for Chatwoot? This isn't a Chatwoot template.

2023-09-22 04:57 UTC, Supernova3339 requested changes

2023-09-22 04:57 UTC, Supernova3339 commented on templates/trudesk/index.ts
elasticsearch URI should not be hardcoded. 

Elasticsearch is NOT a template, so if you'd like to add that too, feel free to do so.

2023-09-22 04:57 UTC, Supernova3339 commented on templates/trudesk/meta.yaml
remove redisServiceName, won't make template possible to use.

2023-09-22 04:59 UTC, Supernova3339 requested changes

2023-09-22 04:59 UTC, Supernova3339 commented on templates/trudesk/index.ts
elasticsearch is not present at all, please add it to index.ts + meta.yaml as searchServiceName

2023-09-22 05:16 UTC, matbrgz commented on templates/trudesk/index.ts
How? :) IDK how to do it. Any idea?

2023-09-22 05:17 UTC, Supernova3339 commented on templates/trudesk/index.ts
Looks like you got it

2023-09-22 16:15 UTC, Supernova3339 requested changes

2023-09-22 16:15 UTC, Supernova3339 commented on templates/trudesk/index.ts
elasticsearch URL is still hardcoded!

2023-09-22 16:41 UTC, matbrgz commented on templates/trudesk/index.ts
As I said in last review, I have no idea how to prooced.

2023-09-22 16:45 UTC, matbrgz commented on templates/trudesk/index.ts
`$(PROJECT_NAME)_${input.searchServiceName}` may work

2026-04-22 14:19 UTC, Ahson-Shaikh commented
Hi, Thanks for the contribution. We already have this template now. Closing PR.

2026-04-22 14:19 UTC, closed without merging