add: Plane *WIP*
easypanel-io/templates pull request #453
Opened 2023-09-21 15:50 UTC by matbrgz

**Description:**

This pull request proposes the integration of "plane.so," a modern collaborative project management platform, into our project. By incorporating "plane.so," we aim to enhance our project management capabilities, streamline task organization, and foster seamless team collaboration.

**Changes:**

- Added necessary files and configurations for "plane.so" integration.
- Integrated "plane.so" functionality for task management, Kanban boards, and real-time collaboration.

**Request for Review:**

I kindly request a thorough review of this pull request to ensure a smooth integration with "plane.so." Feedback on the changes, as well as any suggestions for further improvements, would be highly valuable.

**Checklist:**

- [x] Added "plane.so" integration files and configurations.
- [ ] Integrated "plane.so" project management functionality.

**Additional Notes:**

With the integration of "plane.so," we anticipate improved project organization, enhanced team collaboration, and streamlined workflows. Please review the changes and let me know if there are any additional adjustments or considerations needed.

2023-09-22 03:37 UTC, Supernova3339 reviewed
Please have tests passing so I can approve this PR

2023-09-22 03:47 UTC, matbrgz commented
This one isn't deployed at Docker Hub, they only have a docker compose, is possible to clone docker compose somehow? Could you guide me?

2023-09-22 04:02 UTC, Supernova3339 commented
Plane is on docker hub ( getplane/plane )

On Sep 21 2023, at 10:47 pm, Matheus Breguêz ***@***.***> wrote:
>
>
> This one isn't deployed at Docker Hub, they only have a docker compose, is possible to clone docker compose somehow? Could you guide me?
> —
> Reply to this email directly, view it on GitHub (https://github.com/easypanel-io/templates/pull/453#issuecomment-1730762358), or unsubscribe (https://github.com/notifications/unsubscribe-auth/APESZJWIXB4IS2MR675LNWDX3UC4RANCNFSM6AAAAAA5BYVNCE).
> You are receiving this because you commented.
>

2023-09-22 04:51 UTC, Supernova3339 requested changes

2023-09-22 04:51 UTC, Supernova3339 commented on templates/plane/index.ts
Please make the default username and password configurable.
Also, good luck! I spent a month trying to get this to work.

2023-09-22 04:51 UTC, Supernova3339 commented on templates/plane/meta.yaml
Reminder to change this - makeplane/plane on docker hub for the image (check tags, don't pin latest)

2023-10-28 18:23 UTC, Beedhan commented
Is there any progress on this?

2023-10-30 23:16 UTC, matbrgz commented
> Is there any progress on this?

Help will be appreciated.

2024-03-10 18:32 UTC, marktopper commented
I have made a new PR for this, using the official containers: https://github.com/easypanel-io/templates/pull/501

2024-10-29 00:59 UTC, kellvembarbosa commented
Hi i have problem

2026-04-22 14:03 UTC, closed without merging

2026-04-22 14:03 UTC, Ahson-Shaikh commented
This is pretty old PR which is not actually working. Closing it and would appreciate if you can bring an updated one aligned with the upstream.