add: ever teams
easypanel-io/templates pull request #469
Opened 2023-11-16 07:33 UTC by paradoxe35

This pull request introduces ever-co/ever-teams to the easypanel-io/templates repository. Ever Teams represents an innovative and adaptable platform for work and project management, designed to enhance productivity, teamwork, and oversight for teams across various scales and industries.

Additional Information While ever-co/ever-teams is currently in its development phase, it shows immense promise as a significant contribution to the easypanel-io/templates repository, offering advanced features and capabilities that could be instrumental for users seeking sophisticated management tools.

2023-11-16 07:36 UTC, Supernova3339 commented
Hi, please remove invalid entries from your yaml file.

2023-11-16 07:58 UTC, Supernova3339 commented
Please fix entries in your yaml file, there is incorrect information in the file still.

2023-11-16 08:00 UTC, Supernova3339 requested changes

2023-11-16 08:00 UTC, Supernova3339 commented on templates/ever-teams/meta.yaml
Date not accurate.
Demo link leads to adminer

2023-11-16 08:04 UTC, Supernova3339 requested changes

2023-11-16 08:04 UTC, Supernova3339 commented on templates/ever-teams/meta.yaml
Date still needs fixing...

2023-11-16 08:08 UTC, paradoxe35 commented on templates/ever-teams/meta.yaml
Hey, it’s “October 21, 2023”
How should this be remedied?

2023-11-16 08:09 UTC, Supernova3339 commented on templates/ever-teams/meta.yaml
> Hey, it’s “October 21, 2023” How should this be fixed?

today's month is november, the update isn't based on the release date of the project, it's the publish date of the PR

2023-11-16 08:10 UTC, paradoxe35 commented on templates/ever-teams/meta.yaml
Got it, thanks

2023-11-16 08:17 UTC, Supernova3339 requested changes

2023-11-16 08:17 UTC, Supernova3339 commented on templates/ever-teams/meta.yaml
Email is not built in, must be configured.
[https://github.com/ever-co/ever-teams/blob/develop/apps/web/.env](https://github.com/ever-co/ever-teams/blob/develop/apps/web/.env)

2023-11-16 13:27 UTC, evereq commented on templates/ever-teams/meta.yaml
> +  - name: paradoxe35
@paradoxe35 please change this to:
- name: Ever Co. LTD
- url: https://github.com/ever-co

2026-04-22 13:51 UTC, Ahson-Shaikh commented
Hi @paradoxe35, 

Have you done all the changes?

2026-04-22 16:06 UTC, merged