Add template "DocuSeal"
easypanel-io/templates pull request #494
Opened 2024-02-15 10:17 UTC by vinumweb

Adding template for DocuSeal as per request: https://discord.com/channels/949251825511575562/1207449212485373952/1207449212485373952

2024-02-15 19:59 UTC, tobiasreichel commented on templates/docuseal/index.ts
Please add 

        "mounts": [
          {
            "type": "volume",
            "name": "data",
            "mountPath": "/data"

2024-02-15 20:01 UTC, tobiasreichel requested changes
Add a Volume Mount Point a DocuSeal saves data to disk

2024-03-11 19:52 UTC, marktopper commented
Works like a charm. Great job

2024-03-12 12:01 UTC, marktopper commented
@deiucanta I can vouch that this template works.

2024-04-22 09:25 UTC, serban-alexandru commented
@deiucanta Ready for merge

2024-04-22 10:41 UTC, merged